# Generated by Django 3.2.7 on 2021-11-13 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Practice_title',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title_Content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('contentA', models.CharField(max_length=500)),
                ('contentB', models.CharField(max_length=500)),
                ('contentC', models.CharField(max_length=500)),
                ('contentD', models.CharField(max_length=500)),
                ('correctAnswer', models.CharField(max_length=500, null=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GTEAMS_APP.practice_title')),
            ],
        ),
    ]
