# Generated by Django 3.2.9 on 2021-12-10 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GTEAMS_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_blog',
            name='timeStamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
