# Generated by Django 3.2.8 on 2021-11-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTEAMS_APP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='typeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=10)),
            ],
        ),
    ]
