# Generated by Django 3.2.8 on 2021-11-02 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GTEAMS_APP', '0002_show_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Show',
            new_name='Courses',
        ),
    ]
