# Generated by Django 3.2.8 on 2021-11-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTEAMS_APP', '0003_rename_show_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='image',
        ),
        migrations.AddField(
            model_name='courses',
            name='hey',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
