# Generated by Django 3.2.8 on 2021-11-02 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GTEAMS_APP', '0004_auto_20211102_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='hey',
            new_name='author',
        ),
    ]
