# Generated by Django 3.2.8 on 2021-11-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTEAMS_APP', '0005_rename_hey_courses_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='subject',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
