# Generated by Django 3.2.8 on 2021-11-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTEAMS_APP', '0006_courses_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practice',
            name='correctAnswer',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
