# Generated by Django 3.2.8 on 2021-11-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTEAMS_APP', '0007_auto_20211121_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
