# Generated by Django 3.2.8 on 2021-11-27 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GTEAMS_APP', '0007_courses_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
