# Generated by Django 3.2.8 on 2021-11-27 04:00

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('GTEAMS_APP', '0008_delete_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=50)),
                ('linkVideo', embed_video.fields.EmbedVideoField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('MieuTa', models.TextField()),
                ('costReal', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GTEAMS_APP.typecourse')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GTEAMS_APP.subjects')),
            ],
            options={
                'ordering': ['-added'],
            },
        ),
    ]
