# Generated by Django 3.2.8 on 2021-11-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTEAMS_APP', '0008_courses_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='costReal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
