# Generated by Django 3.2.9 on 2021-11-28 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GTEAMS_APP', '0010_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='article',
            new_name='article_quiz',
        ),
    ]
