# Generated by Django 3.2.8 on 2021-12-02 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GTEAMS_APP', '0013_auto_20211128_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masp', models.IntegerField(default=0)),
                ('subject', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('costReal', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GTEAMS_APP.subjects')),
            ],
        ),
    ]
