# Generated by Django 3.2.8 on 2021-12-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTEAMS_APP', '0014_auto_20211202_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
