# Generated by Django 3.2.9 on 2021-12-05 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GTEAMS_APP', '0017_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_blog',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GTEAMS_APP.blogcomment'),
        ),
    ]
