# Generated by Django 3.2.7 on 2021-12-11 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GTEAMS_APP', '0018_auto_20211206_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_blog',
            name='timeStamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
