# Generated by Django 3.2.8 on 2021-12-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GTEAMS_APP', '0019_alter_article_blog_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='isCart',
            field=models.BooleanField(default=False),
        ),
    ]
